# Generated by Django 5.1.6 on 2025-04-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='accepted_payments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(default='Used', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='empty.png', upload_to='listing_images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
